version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    groups:
      kotlin:
        patterns:
          - "io.gitlab.arturbosch.detekt"
          - "org.jlleitschuh.gradle.ktlint"
    ignore:
      - dependency-name: "org.jetbrains.kotlin:*"
      - dependency-name: "com.google.devtools.ksp"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
