/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.xalvarez.githubteamdashboard

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testGitHubTeamDashboardApplicationHasAGreeting() {
        val classUnderTest = GitHubTeamDashboardApplication()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
