/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.xalvarez.githubteamdashboard

class GitHubTeamDashboardApplication {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(GitHubTeamDashboardApplication().greeting)
}
