name: Upload packages

on:
  push:
    branches:
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout git branch
      uses: actions/checkout@v1
    - name: Install JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build application
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: clean build
    - name: Push docker image
      run: |
        VERSION=$(date +%s)
        docker login docker.pkg.github.com --username xalvarez --password ${{ secrets.GITHUB_TOKEN }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/xalvarez/github-team-dashboard/github-team.dashboard:${VERSION}
        docker push ddocker.pkg.github.com/xalvarez/github-team-dashboard/github-team.dashboard:${VERSION}
